spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://syh80882.cafe24.com/syh80882'
    username: syh80882
    password: abc123!@
    sql-script-encoding: utf-8
  messages:
    basename: messages/messages, messages/error
